# Generated by Django 4.1.2 on 2022-10-18 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
