# Generated by Django 4.1.2 on 2022-10-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_user_following_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temp_id',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
