# Generated by Django 4.1.2 on 2022-10-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_temp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='temp_id',
        ),
    ]
