# Generated by Django 4.1.2 on 2022-10-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_avatar_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/images/default-user-image.png', null=True, upload_to='images/'),
        ),
    ]
