# Generated by Django 4.1.2 on 2022-10-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default-user-image.png', null=True, upload_to='images/'),
        ),
    ]
