# Generated by Django 4.1.2 on 2022-10-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
